# Imagen en lo que se basara nuestra imagen , es recomendable que se coloque version especificas
FROM node:18-alpine3.15

# Set working directory
# Crea un directorio
RUN mkdir -p /var/www/pokedex 
# Estable un directorio para no tener que usar la ruta en todos lados
WORKDIR /var/www/pokedex

# Copiar el directorio y su contenido
COPY . ./var/www/pokedex
COPY package.json tsconfig.json tsconfig.build.json /var/www/pokedex/
# RUN npm install --prod // instalaria solo las dependencia de produccion
RUN npm install 
RUN npm run build


# Dar permiso para ejecutar la applicación // recomendado
RUN adduser --disabled-password pokeuser
RUN chown -R pokeuser:pokeuser /var/www/pokedex
USER pokeuser

# Limpiar el caché
# RUN yarn cache clean --force

EXPOSE 3000

# Comando que va a correr al terminar todo
CMD [ "npm","start" ]